/* Sentinel V3 — GitHub Pages compatible runtime. No /api dependency. */
(()=>{'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const NVD='https://services.nvd.nist.gov/rest/json/cves/2.0';
const pageData={overview:{title:'Overview',html:`<section class="workspace hero"><div><span class="eyebrow">SECURITY OPERATIONS</span><h2>Understand your attack surface.<br><em>Before it becomes a problem.</em></h2><p>Sentinel V3 is a browser-first security intelligence console. Every result is labelled by evidence state.</p><div class="actions"><button class="primary" data-go="domain">Analyze a Domain →</button><button class="ghost" data-go="cve">Explore CVEs</button></div></div><div class="radar"><span>ENGINE<br><b>READY</b></span></div></section><section class="cards"><button class="card" data-go="domain"><small>01</small><h3>Domain Intelligence</h3><p>Validate and inspect a public hostname.</p><span>Open module ↗</span></button><button class="card" data-go="headers"><small>02</small><h3>Security Headers</h3><p>Understand browser-verifiable header evidence.</p><span>Open module ↗</span></button><button class="card" data-go="tls"><small>03</small><h3>TLS / SSL</h3><p>Check HTTPS and HSTS signals.</p><span>Open module ↗</span></button><button class="card" data-go="dns"><small>04</small><h3>DNS Intelligence</h3><p>Resolve public DNS records.</p><span>Open module ↗</span></button></section>`},
 domain:{title:'Domain Intel',html:module('DOMAIN INTELLIGENCE','Target validation and discovery','Enter a public hostname. Browser-only deployment limits what can be verified.','Analyze Domain','domain')},
 headers:{title:'Security Headers',html:module('SECURITY HEADERS','HTTP security-control review','Arbitrary response headers cannot be reliably inspected cross-origin from a static browser deployment.','Check Availability','headers')},
 tls:{title:'TLS / SSL',html:module('TLS / SSL','Transport security posture','Browser JavaScript cannot expose a remote certificate chain or negotiated TLS details for arbitrary origins.','Check HTTPS','tls')},
 dns:{title:'DNS Intelligence',html:module('DNS INTELLIGENCE','Public DNS evidence','Resolve public records through DNS-over-HTTPS. Results are labelled as externally sourced evidence.','Resolve DNS','dns')},
 owasp:{title:'OWASP Security Center',html:`<section class="workspace module"><span class="eyebrow">OWASP-ALIGNED CONTROLS</span><h2>Security Control Center</h2><p>Use these control families as an evidence-first review checklist.</p><div class="moduleGrid"><div class="panel"><h3>Control Families</h3><p>${['A01 Broken Access Control','A02 Cryptographic Failures','A03 Injection','A04 Insecure Design','A05 Security Misconfiguration','A06 Vulnerable Components','A07 Authentication Failures','A08 Software/Data Integrity','A09 Logging & Monitoring','A10 SSRF'].map(x=>`<span class="tag">${x}</span>`).join('')}</p></div><div class="panel"><h3>Evidence policy</h3><div class="notice">Sentinel never marks a control vulnerable without supporting evidence.</div></div></div></section>`},
 cve:{title:'CVE Explorer',html:`<section class="workspace"><span class="eyebrow">NVD INTELLIGENCE</span><h2 style="font-size:30px;margin:10px 0">CVE Explorer</h2><p style="color:#737d8e">Search the public NVD CVE API. No API key is embedded in the site.</p><div class="toolrow"><input id="cveq" placeholder="CVE-2026-40991 or vulnerability keyword"><button class="primary" id="cveSearch">Search NVD →</button></div><div id="results"></div></section>`}};
function module(label,title,text,button,kind){return `<section class="workspace module"><span class="eyebrow">${label}</span><h2>${title}</h2><p>${text}</p><div class="moduleGrid"><div class="panel"><h3>Start analysis</h3><div class="toolrow"><input id="${kind}q" placeholder="example.com"><button class="primary" data-run="${kind}">${button} →</button></div><div id="${kind}out" class="notice" style="margin-top:15px">No analysis started.</div></div><div class="panel"><h3>Evidence state</h3><div class="metric">NOT TESTED</div><p>Verified results appear only when the browser can obtain evidence.</p></div></div></section>`}
function go(p){location.hash=p}function render(){let p=location.hash.slice(1)||'overview';if(!pageData[p])p='overview';$('#title').textContent=pageData[p].title;$('#content').innerHTML=pageData[p].html;document.querySelectorAll('#nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===p));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-run]').forEach(b=>b.onclick=()=>run(b.dataset.run));const cs=$('#cveSearch');if(cs)cs.onclick=searchCVE;}
async function run(kind){const q=$('#'+kind+'q')?.value.trim(),out=$('#'+kind+'out');if(!q){out.innerHTML='<span class="error">Enter a hostname first.</span>';return}if(kind==='dns'){out.textContent='Querying public DNS evidence…';try{const r=await fetch('https://dns.google/resolve?name='+encodeURIComponent(q)+'&type=ALL');if(!r.ok)throw Error('DNS service unavailable');const d=await r.json();const answers=d.Answer||[];out.innerHTML=`<b class="ok">VERIFIED · External DNS evidence</b><br>${answers.length?answers.map(x=>`<span class="tag">${esc(x.name)} → ${esc(x.data)}</span>`).join(''):'No answer records returned.'}<br><small>Source: Google Public DNS JSON API · ${new Date().toLocaleTimeString()}</small>`}catch(e){out.innerHTML=`<b class="error">UNAVAILABLE</b><br>${esc(e.message)}. No finding was inferred.`}return}if(kind==='domain'){try{const u=new URL(/^https?:\/\//i.test(q)?q:'https://'+q);out.innerHTML=`<b class="ok">VALIDATED</b><br>Hostname: <b>${esc(u.hostname)}</b><br>Protocol: <b>${esc(u.protocol.replace(':','').toUpperCase())}</b><br><small>URL syntax and hostname validated locally.</small>`}catch(e){out.innerHTML='<b class="error">INVALID TARGET</b><br>Enter a valid public hostname.'}return}if(kind==='tls'){out.innerHTML=`<b>VERIFIED — Browser reachability only</b><br>Target uses HTTPS syntax. Certificate, cipher and TLS-version details are <b>NOT AVAILABLE</b> to ordinary cross-origin JavaScript.`;return}out.innerHTML=`<b>NOT AVAILABLE</b><br>Reliable arbitrary-origin HTTP response-header inspection requires a server-side fetch or compatible CORS response. Sentinel will not fabricate a header grade.`}
async function searchCVE(){const q=$('#cveq').value.trim(),r=$('#results');if(!q){r.innerHTML='<div class="notice" style="margin-top:15px">Enter a CVE ID or keyword.</div>';return}r.innerHTML='<div class="notice" style="margin-top:15px">Searching NVD…</div>';try{const url=NVD+(q.toUpperCase().startsWith('CVE-')?'?cveId='+encodeURIComponent(q):'?keywordSearch='+encodeURIComponent(q)+'&resultsPerPage=10');const res=await fetch(url);if(!res.ok)throw Error('NVD returned HTTP '+res.status);const d=await res.json();const arr=d.vulnerabilities||[];r.innerHTML=arr.length?arr.map(v=>{const c=v.cve||{},desc=(c.descriptions||[]).find(x=>x.lang==='en')?.value||'No English description';const cvss=c.metrics?.cvssMetricV31?.[0]?.cvssData?.baseScore??c.metrics?.cvssMetricV30?.[0]?.cvssData?.baseScore??'—';return `<div class="cve"><code>${esc(c.id||'Unknown')}</code><b>${esc(desc)}</b><small>CVSS: ${esc(cvss)} · Published: ${esc(c.published||'—')}</small></div>`}).join(''):'<div class="notice" style="margin-top:15px">No CVEs found.</div>'}catch(e){r.innerHTML=`<div class="notice error" style="margin-top:15px"><b>NVD unavailable.</b><br>${esc(e.message)}<br>No vulnerability conclusion was inferred.</div>`}}
window.addEventListener('hashchange',render);render();
})();
