const K='te-v3';
const A=document.querySelector('#app');
const fallback={questions:[],attempts:[],templates:[]};
let S=(()=>{try{return JSON.parse(localStorage.getItem(K))||fallback}catch{return fallback}})();
if(!Array.isArray(S.questions))S.questions=[];
if(window.BUILTIN_QUESTIONS?.length){const ids=new Set(S.questions.map(q=>q.id));S.questions.push(...window.BUILTIN_QUESTIONS.filter(q=>!ids.has(q.id)));localStorage.setItem(K,JSON.stringify(S));}
const E={stet:{short:'STET CS',name:'Bihar STET Paper II — Computer Science',n:150,m:150,neg:0,sections:[['Computer Science',100],['Teaching & Eligibility',50]],cut:'General 50% · Reserved 40%'},tre:{short:'TRE 4.0 CS',name:'BPSC TRE 4.0 — Senior Secondary CS',n:150,m:150,neg:-1/3,sections:[['Language (qualifying)',30],['General Studies',40],['Computer Science',80]],cut:'Part I qualifying · merit uses Parts II + III'}};
const esc=x=>String(x??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=s=>String(Math.floor(Math.max(0,s)/60)).padStart(2,'0')+':'+String(Math.max(0,s)%60).padStart(2,'0');
const save=()=>localStorage.setItem(K,JSON.stringify(S));
function layout(title,body,active='home'){A.innerHTML=`<div class="app-shell"><aside><div class="brand"><span class="brand-mark">TE</span><div><b>Test Engine</b><small>V3 · Production</small></div></div><nav><button class="nav ${active==='home'?'active':''}" onclick="go('home')"><i>⌂</i>Dashboard</button><button class="nav ${active==='builder'?'active':''}" onclick="go('builder')"><i>＋</i>Test Builder</button><button class="nav ${active==='attempts'?'active':''}" onclick="go('attempts')"><i>◷</i>Attempts</button></nav><div class="side-note"><b>Local & Private</b><span>All product content is managed in the application.</span></div></aside><main><header><div><span class="kicker">TEST ENGINE</span><h1>${title}</h1></div></header>${body}</main></div>`}
function go(p){if(p==='builder')return builder();if(p==='attempts')return attempts();return home()}
function home(){layout('Dashboard',`<section class="hero"><div><span class="pill">● SYSTEM READY</span><h2>Build. Practice. <em>Improve.</em></h2><p>Premium exam-focused mock testing for Bihar STET and BPSC TRE 4.0 Computer Science.</p><div class="hero-actions"><button class="primary" onclick="builder()">Create Mock Test →</button></div></div><div class="hero-orb"><strong>150</strong><span>MAX QUESTIONS</span></div></section><div class="section-head"><span class="kicker">EXAM PRESETS</span><h3>Choose your preparation track</h3></div><div class="cards">${Object.values(E).map(e=>`<article class="exam-card"><span class="number">${e.short}</span><h3>${e.name}</h3><p>${e.n} questions · ${e.m} minutes · ${e.neg===0?'No negative marking':'Negative marking'}</p><button class="secondary" onclick="configure('${e.short}')">Configure →</button></article>`).join('')}</div><div class="stats"><div><span>QUESTIONS</span><b>${S.questions.length}</b></div><div><span>ATTEMPTS</span><b>${S.attempts.length}</b></div><div><span>TEMPLATES</span><b>${S.templates.length}</b></div><div><span>MODE</span><b>LOCAL</b></div></div>`)}
function builder(){layout('Test Builder',`<div class="builder-grid"><section class="panel"><span class="kicker">EXAM PRESETS</span><h3>Configure a test</h3><div class="choice-grid">${Object.values(E).map(e=>`<button class="choice" onclick="configure('${e.short}')"><b>${e.short}</b><span>${e.n} Q · ${e.m} min</span></button>`).join('')}<button class="choice" onclick="custom()"><b>Custom Test</b><span>Count · time · marking</span></button></div><div id="config"><p class="muted">Choose a preset to continue.</p></div></section><section class="panel"><span class="kicker">ENGINE</span><h3>Premium CBT</h3><div class="rule"><span>Navigation</span><b>Question palette</b></div><div class="rule"><span>Timing</span><b>Per-question tracking</b></div><div class="rule"><span>Review</span><b>Detailed post-test analysis</b></div></section></div>`,'builder')}
function configure(short){builder();const e=Object.values(E).find(x=>x.short===short);document.querySelector('#config').innerHTML=`<div class="config"><div class="config-row"><label>Exam</label><strong>${e.name}</strong></div><div class="config-row"><label>Structure</label><strong>${e.sections.map(x=>x[1]+' '+x[0]).join(' · ')}</strong></div><div class="config-row"><label>Duration</label><strong>${e.m}:00</strong></div><div class="config-row"><label>Marking</label><strong>${e.neg===0?'No negative marking':'−1/3 default'}</strong></div><div class="config-row"><label>Qualifying / cutoff</label><strong>${e.cut}</strong></div><button class="primary full" onclick="start('${short}')">Start ${e.short} →</button></div>`}
function custom(){builder();document.querySelector('#config').innerHTML=`<div class="config"><label>Questions<input id="cn" type="number" min="1" max="150" value="20"></label><label>Minutes<input id="cm" type="number" min="1" max="300" value="30"></label><label>Wrong-answer marks<input id="cw" type="number" min="-10" max="0" step=".01" value="0"></label><button class="primary full" onclick="startCustom()">Start Custom →</button></div>`}
function startCustom(){startSession({short:'CUSTOM',name:'Custom Mock Test',n:+document.querySelector('#cn').value,m:+document.querySelector('#cm').value,neg:+document.querySelector('#cw').value,sections:[['Custom',+document.querySelector('#cn').value]]})}
function start(short){startSession(Object.values(E).find(e=>e.short===short))}
function startSession(e){let pool=e.short==='STET CS'?S.questions.filter(q=>q.bank==='STET CS'):e.short==='TRE 4.0 CS'?S.questions.filter(q=>q.bank==='TRE 4.0 CS'):S.questions;if(pool.length<e.n){alert(`This test needs ${e.n} questions. The product bank currently has ${pool.length} matching questions.`);return}pool=[...pool].sort(()=>Math.random()-.5).slice(0,e.n);test={e,q:pool,a:Array(e.n).fill(null),st:Array(e.n).fill('not'),i:0,left:e.m*60,last:Date.now()};renderTest()}
let timer=null,test=null;
function renderTest(){clearInterval(timer);const t=test,q=t.q[t.i];A.innerHTML=`<div class="test-shell"><header class="test-header"><div class="brand"><span class="brand-mark">TE</span><b>${t.e.short}</b></div><div class="timer" id="clock">${fmt(t.left)}</div><button class="danger" onclick="submitTest()">Submit Test</button></header><div class="test-body"><aside class="palette"><h3>Question Palette</h3><div class="legend"><span>Green = Answered</span><span>Yellow = Review</span></div><div class="palette-grid">${t.q.map((_,i)=>`<button class="pbtn ${t.st[i]}" onclick="jump(${i})">${i+1}</button>`).join('')}</div></aside><section class="question"><div class="q-meta"><span>Question ${t.i+1} of ${t.q.length}</span><span>${esc(q.topic||q.section||'General')}</span></div><h2>${esc(q.question)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option ${t.a[t.i]===i?'selected':''}" onclick="choose(${i})"><span>${String.fromCharCode(65+i)}</span>${esc(o)}</button>`).join('')}</div><div class="test-controls"><button class="secondary" onclick="clearA()">Clear Response</button><button class="review" onclick="reviewQ()">Mark for Review & Next</button><button class="primary" onclick="nextQ()">Save & Next →</button></div></section></div></div>`;timer=setInterval(()=>{test.left--;const c=document.querySelector('#clock');if(c)c.textContent=fmt(test.left);if(test.left<=300&&c)c.classList.add('warning');if(test.left<=0)finish()},1000)}
function track(){test.last=Date.now()}function choose(i){test.a[test.i]=i;test.st[test.i]='answered';renderTest()}function clearA(){test.a[test.i]=null;test.st[test.i]='not';renderTest()}function reviewQ(){test.st[test.i]=test.a[test.i]===null?'review':'answered-review';nextQ()}function nextQ(){test.i=Math.min(test.i+1,test.q.length-1);renderTest()}function jump(i){test.i=i;renderTest()}function submitTest(){if(confirm(`Submit test?\nAnswered: ${test.a.filter(x=>x!==null).length}\nUnanswered: ${test.a.filter(x=>x===null).length}`))finish()}
function finish(){clearInterval(timer);let c=0,w=0;test.q.forEach((q,i)=>{if(test.a[i]===q.answer)c++;else if(test.a[i]!==null)w++});const score=c+w*(test.e.neg||0);const a={id:crypto.randomUUID(),exam:test.e.short,name:test.e.name,score,correct:c,wrong:w,unanswered:test.q.length-c-w,total:test.q.length,time:test.e.m*60-test.left,date:new Date().toISOString()};S.attempts.push(a);save();report(a)}
function report(a){A.innerHTML=`<div class="report"><header><div><span class="kicker">POST-TEST ANALYSIS</span><h1>${esc(a.exam)}</h1></div><button class="primary" onclick="go('attempts')">Attempt History</button></header><section class="score-grid"><div class="score-card"><span>SCORE</span><b>${a.score.toFixed(2)}</b><small>out of ${a.total}</small></div><div class="score-card"><span>ACCURACY</span><b>${a.total?Math.round(a.correct/a.total*100):0}%</b><small>${a.correct} correct · ${a.wrong} wrong</small></div><div class="score-card"><span>TIME</span><b>${fmt(a.time)}</b><small>time taken</small></div><div class="score-card"><span>UNATTEMPTED</span><b>${a.unanswered}</b><small>questions</small></div></section><section class="panel report-panel"><h3>Attempt recorded locally</h3><p>Your result is stored in this browser.</p><button class="secondary" onclick="go('attempts')">View Attempts</button></section></div>`}
function attempts(){layout('Attempt History',`<section class="panel"><h3>Previous attempts</h3>${S.attempts.slice().reverse().map(a=>`<div class="history-row"><b>${esc(a.exam)}</b><span>${a.score.toFixed(2)} / ${a.total} · ${Math.round(a.correct/a.total*100)}% accuracy</span><small>${new Date(a.date).toLocaleString()}</small></div>`).join('')||'<p class="muted">No completed attempts yet.</p>'}`,'attempts')}
try{home()}catch(err){console.error(err);A.innerHTML='<main style="padding:48px;font-family:Inter,system-ui,sans-serif"><h1>Test Engine</h1><p>Production is loading. Please refresh shortly.</p></main>'}
